# Generated by Django 5.2.7 on 2025-11-17 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eb_service_num', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cus_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cus_address', models.TextField(blank=True, null=True)),
                ('cus_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('cus_password', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('tariff_category', models.CharField(choices=[('Domestic', 'Domestic'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('emp_con_num', models.CharField(blank=True, max_length=15, null=True)),
                ('emp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emp_password', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('emp_address', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.CharField(choices=[('North Region', 'North Region'), ('South Region', 'South Region'), ('East Region', 'East Region'), ('West Region', 'West Region'), ('Central Region', 'Central Region')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TariffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eb_service_num', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('TariffCategory', models.CharField(max_length=10)),
                ('reading_date', models.DateField()),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('bill_date', models.DateField(default=django.utils.timezone.localdate)),
                ('previous_reading', models.IntegerField()),
                ('current_reading', models.IntegerField()),
                ('units_consumed', models.IntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=50)),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='myapp.bill')),
            ],
        ),
        migrations.CreateModel(
            name='previewreadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('eb_service_num', models.CharField(max_length=20)),
                ('previous_reading', models.IntegerField()),
                ('current_reading', models.IntegerField()),
                ('units_consumed', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='per_unit_price_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('starting_unit', models.IntegerField()),
                ('ending_unit', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_unit_prices', to='myapp.customer')),
                ('eb_service_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_by_service_num', to='myapp.customer', to_field='eb_service_num')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.tariffcategory')),
            ],
        ),
    ]
